[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  port = 8888
  targetPort = 5173
  framework = "#custom"

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning for client-side API keys
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

# Function configuration - applies to all functions
[functions]
  # Use esbuild for faster builds
  node_bundler = "esbuild"
  # Note: Free tier has 10s timeout, Pro has 26s
  # Configured per-function in Netlify UI if needed

# Production branch configuration
[context.production]
  command = "npm run build"

# Branch deploy configuration - auto-deploy all branches
[context.branch-deploy]
  command = "npm run build"

# Specific configuration for Main-Prompt-Gen-V2 branch
[context.Main-Prompt-Gen-V2]
  command = "npm run build"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/gemini/text"
  to = "/.netlify/functions/gemini-text"
  status = 200
  force = true

[[redirects]]
  from = "/api/gemini/images"
  to = "/.netlify/functions/gemini-images"
  status = 200
  force = true

# Image generation endpoint using Vertex AI Imagen 3
[[redirects]]
  from = "/api/gemini/image-gen"
  to = "/.netlify/functions/gemini-image-gen"
  status = 200
  force = true

# Prompt enhancement endpoint using Gemini Flash 2.5
[[redirects]]
  from = "/api/gemini/enhance-prompt"
  to = "/.netlify/functions/gemini-enhance-prompt"
  status = 200
  force = true

[[redirects]]
  from = "/api/storyboards/plan"
  to = "/.netlify/functions/storyboards-plan"
  status = 200
  force = true

[[redirects]]
  from = "/api/storyboards/generate"
  to = "/.netlify/functions/storyboards-generate"
  status = 200
  force = true

[[redirects]]
  from = "/api/storyboards/generate-frame"
  to = "/.netlify/functions/storyboards-generate-frame"
  status = 200
  force = true

[[redirects]]
  from = "/api/storyboards/edit"
  to = "/.netlify/functions/storyboards-edit"
  status = 200
  force = true

[[redirects]]
  from = "/api/storyboards/extend"
  to = "/.netlify/functions/storyboards-extend"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200
  force = true

[[redirects]]
  from = "/api/check-env"
  to = "/.netlify/functions/check-env"
  status = 200
  force = true

# Performance optimizations - Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Single-page app fallback for Vite (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
